version: "3.7"
services:
  nginx:
    container_name: nginx
    image: docker.io/nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    depends_on: jenkins
    restart: always
  jenkins:
    container_name: jenkins
    image: docker.io/jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
volumes:
  jenkins_home: